# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "17b048405a3e2ffe901be65f5783837d"
application_url = "https://local.chr33s.dev"
embedded = true
name = "ShopFlare"
handle = "shopflare"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_app_proxy"
optional_scopes = [ "write_products" ]
use_legacy_install_flow = false

[app_proxy]
url = "https://local.chr33s.dev/apps/shopflare"
subpath = "shopflare"
prefix = "apps"

[auth]
redirect_urls = [ "https://local.chr33s.dev/shopify/auth/callback" ]

[build]
automatically_update_urls_on_dev = false
dev_store_url = "glue-dev-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/shopify/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  topics = [ "app/scopes_update", "app/uninstalled" ]

[pos]
embedded = false
