// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSION_STORAGE: KVNamespace;
	NODE_VERSION: string;
	SHOPIFY_API_KEY: string;
	SHOPIFY_API_SECRET_KEY: string;
	SHOPIFY_APP_ENV: string;
	SHOPIFY_APP_LOG_LEVEL: string;
	SHOPIFY_APP_URL: string;
	WEB_VITALS: AnalyticsEngineDataset;
	WEBHOOK_QUEUE: Queue;
	ASSETS: Fetcher;
}
