// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSION_STORAGE: KVNamespace;
	CLOUDFLARE_API_TOKEN: string;
	NODE_VERSION: string;
	SHOPIFY_API_KEY: string;
	SHOPIFY_API_SECRET_KEY: string;
	SHOPIFY_APP_ENV: string;
	SHOPIFY_APP_URL: string;
}
