#graphql
mutation MetafieldDelete($metafields: [MetafieldIdentifierInput!]!) {
	metafieldsDelete(metafields: $metafields) {
		deletedMetafields {
			key
			namespace
			ownerId
		}
		userErrors {
			field
			message
		}
	}
}
