#graphql
mutation BulkOperationRunQuery($query: String!) {
	bulkOperationRunQuery(query: $query) {
		bulkOperation {
			errorCode
			id
			partialDataUrl
			status
			type
			url
		}
		userErrors {
			field
			message
		}
	}
}
