#graphql
mutation MetafieldDefinitionCreate($definition: MetafieldDefinitionInput!) {
	metafieldDefinitionCreate(definition: $definition) {
		createdDefinition {
			id
			name
		}
		userErrors {
			code
			field
			message
		}
	}
}
