#graphql
mutation FileCreate($files: [FileCreateInput!]!) {
	fileCreate(files: $files) {
		files {
			fileErrors {
				code
				details
				message
			}
			id
		}
		userErrors {
			code
			field
			message
		}
	}
}
