name: Cloudflare

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci
      - run: npm run build --ignore-scripts
        env:
          SHOPIFY_API_KEY: ${{ env.SHOPIFY_API_KEY }}
      - run: npm test
      - uses: github/codeql-action/analyze@v3
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
