name: Cloudflare

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: [releases/*]

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    name: Build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci
      - run: npm run build --ignore-scripts
        env:
          SHOPIFY_API_KEY: ${{ vars.SHOPIFY_API_KEY }}
      - run: npm test
      - uses: github/codeql-action/analyze@v3
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  preview:
    name: Preview
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload --message=${{ github.ref_name }} --tag=${{ github.sha }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions deploy
