name: Release

on:
  push:
    tags:
      - releases/*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: actions/github-script@v7
        with:
          script: |
            const tag_name = context.ref;
            const name = tag_name.replace(/^refs\/tags\/releases\//, '');
            const prerelease = name.startsWith("0.");
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            github.rest.repos.createRelease({
              name,
              owner,
              prerelease,
              repo,
              tag_name,
            });
